### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by cheack** [Neoflow/Bootstrap-Fileselect#3]
If there are too many files are selected, we see a text that doesn't fit into the field:
<img width="583" alt="2020-03-26_17-13-03" src="https://user-images.githubusercontent.com/668493/77629862-23317a00-6f85-11ea-9e46-1a3fd049e866.png">

**Comment by Alpine418** [comment]
Sorry, for my late response. I will see what I can improve.

**Comment by Alpine418** [comment]
Should be fixed now.

**Comment by Alpine418** [comment]
Forgot to publish on npmjs.org. The package there is now up to date too.

https://www.npmjs.com/package/@neoflow/bootstrap-fileselect
